version: '3'
services:
    # Shared Auth Service
    auth:
      container_name: ursif_auth
      build:
        context: ./modules/auth
      ports:
        - "9999:6379"
    
    # REST Storage Interface
    rest:
      container_name: ursif.rest
      build:
        context: ./modules/rest
      ports:
        - "9997:27017"

    # Message Bus for User
    events:
      container_name: ursif.bus
      build:
        context: ./modules/bus
      ports:
        - "9996:6379"
    