version: '3'
services:
    # Shared Auth Service
    auth:
      container_name: ursif_auth
      build:
        context: ./modules/auth
      ports:
        - "9999:6379"
    
    # REST Storage Interface
    rest:
      container_name: ursif_rest
      build:
        context: ./modules/rest
      ports:
        - "9998:27017"

    # user:
    #   container_name: ursif_user
    #   build:
    #     context: ./modules/user
    #   ports:
    #     - "9996:6379"
    